parameters:
    # Directry separator
    server.separator: /

    # Application settings
    app.path: J:\wamp\www\engi
    app.name: Engi
    app.version: 1.0
    app.command.name.argument: command_name

    # Do not change
    app.path.src: %app.path%%server.separator%src
    config.paths:
      - %app.path.src%%server.separator%config
      - %app.path.src%%server.separator%config%server.separator%services
    config.files.app: app.yml
    config.files.db: db.yml
